# Generated by Django 5.0.6 on 2024-08-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_loanenquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanenquiry',
            old_name='Bank',
            new_name='bank',
        ),
    ]
