# Generated by Django 5.0.6 on 2024-08-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_loanenquiry_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanEnquiry',
        ),
    ]
