# Generated by Django 5.0.6 on 2024-08-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_delete_loanenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanEnquiry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('loan', models.CharField(max_length=100)),
                ('bank', models.CharField(max_length=100)),
                ('candidate', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.CharField(max_length=15)),
                ('tenure', models.CharField(max_length=15)),
                ('adhar', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('pan', models.FileField(blank=True, default='', null=True, upload_to='uploads')),
                ('status', models.CharField(default='Pending', max_length=100)),
            ],
        ),
    ]
